[package]
name = "cardgame"
version = "0.1.0"
authors = ["kyle merfeld <kmerfeld1@gmail.com>"]

[dependencies]
serde = "1.0.4"
serde_json = "1.0.2"
serde_derive = "1.0.8"
rand = "0.3"
text_io = "0.1.6"
