[package]
name = "cardgame_board"
version = "0.1.0"
authors = ["kyle merfeld <kmerfeld1@gmail.com>"]

[dependencies]
serde = "1.0.4"
serde_json = "1.0.2"
serde_yaml = "0.7.1"
serde_derive = "1.0.8"
rand = "0.3"
